main: rip.diamond.practice.Eden
name: Eden
version: '${version}'
author: [cystol, GoodestEnglish]
description: The best practice plugin with premium features
depend: [WorldEdit, FastAsyncWorldEdit, ProtocolLib]
softdepend: [ViaVersion, PlaceholderAPI, Citizens]
